# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

# Optionally declare the Python requirements required to build your docs
conda:
  environment: environment-dev.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - complete
