FROM python:3.11

WORKDIR /opt/ragna

COPY requirements-pydatanyc2023.lock .
RUN pip install --progress-bar=off --requirement requirements-pydatanyc2023.lock

RUN pip install --progress-bar=off --no-deps ragna==0.1.2

WORKDIR /var/ragna
ENTRYPOINT []
CMD ["ragna", "--help"]

COPY ragna_pydatanyc2023.py .
ENV PYTHONPATH="/var/ragna:{$PYTHONPATH}"

COPY ragna-pydatanyc2023.toml .
ENV RAGNA_CONFIG=/var/ragna/ragna-pydatanyc2023.toml

# FIXME: can we move this to local cache root?
ENV LANCEDB_CONFIG_DIR=/var/ragna/lancedb
