name: ragna-dev
channels:
  - conda-forge
dependencies:
  - python =3.9
  - redis-server
  - pip
  - aiofiles
  - emoji

  # for development only
  - pre-commit

  # For use with Panel branch for Chat Interface
  - nodejs

  - pip:
    - jupyter
    - python-dotenv
    - boto3
    - pytest >=6
    - tomlkit
    - mypy
    # documentation
    - sphinx
    - myst-parser
    - sphinx-copybutton
    - furo
    - sphinx-design
    - sphinx-inline-tabs
    - sphinxext-opengraph

    # Temporary dependency for the new Panel Chat Interface.
    # TODO: remove this dependency once the new Panel Chat Interface is released,
    # and pin Panel's version
    # - git+https://github.com/holoviz/panel@chat_components
    - git+https://github.com/holoviz/panel@a0d0ba29f296547c4fa5968f92ecb12cdadfad47
    
