name: ragna-dev
channels:
  - conda-forge
dependencies:
  - python =3.9
  - pip
  - redis-server
  - jupyter
  - python-dotenv
  - boto3
  - pytest >=6
  - tomlkit
  - mypy
  - pip
  # documentation
  - pip:
    - sphinx
    - furo
    - myst-parser
    - sphinx-design
    - sphinx-inline-tabs
    - sphinx-copybutton
    - sphinxext-opengraph
