local_cache_root = "/var/ragna"

[core]
document = "ragna_pydatanyc2023.S3Document"
source_storages = ["ragna.source_storages.RagnaDemoSourceStorage"]
assistants = ["ragna.assistants.RagnaDemoAssistant"]

[api]
authentication = "ragna.core.RagnaDemoAuthentication"
upload_token_ttl = 300

[ui]
