"""
# Basics of the REST API

Ragna was designed to help you quickly build custom RAG and LLM powered web
applications. You can leverage the built-in [REST API](../references/rest-api.md) (which
is consistent with the [Python API](../references/python-api.md) designed for
experimentation) for application development.

This tutorial walks you through basic steps of using the REST API for creating a chat
service.
"""

# %%
# ## Step 1: Setup RAG configuration
#
# Ragna workflows start with a configuration. You can select components like the
# assistant (LLM) and source storage (vector database) and set options like the API
# endpoint and cache location.
#
# Use the CLI wizard and pick the first option to generate a basic configuration file:
#
# ```bash
# ragna init
# ```
#
# Create a configuration using the file:

from ragna.deploy import Config

config = Config()
config.to_file("ragna.toml", force=True)

# %%
# !!! tip
#
#     Learn more in [How to set configuration](../how-tos/set-configuration.md).
#
# ## Step 2: Start and connect to the API
#
# You can use the [`ragna api`](../references/cli.md#ragna-api) command to start the
# REST API from your terminal. The command includes a `--config` option where you can
# chose your preferred configuration.
#
# The `ragna.toml` file generated by the CLI wizard will be used by default:
