name: "Feature request ✨"
description: "Create a feature request to help Ragna improve"
title: "[ENH] - <title>"
labels: ["type: enhancement 💅"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for using Ragna and taking the time to contribute to this project.
  - type: textarea
    attributes:
      label: Feature description
      description: |
        Describe "what" you are proposing.
        Provide as much context as possible and link to related issues and/or pull requests.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Value and/or benefit
      description: |
        What is the value of adding this feature, and who will benefit from it?
        Include any information that could help us prioritize the issue.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!
    validations:
      required: false
