name: "Usage question 🙋🏽‍♀️"
description: "Create a report to help us fix something that is currently broken."
title: "[Q/A] - <title>"
labels: ["type: question 🤔"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question!
        Before asking a question, make sure it hasn't already been addressed by searching through
        the documentation and past issues in this repository.

  - type: textarea
    attributes:
      label: Question
      description: |
        Share your question.
        Include information about what you're trying to do and what you've tried so far.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal example
      description: |
        Provide a minimal code example and detailed step-by-step guidelines to reproduce the error.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Tracebacks? Screenshots? Anything that will give us more context!
    validations:
      required: false
