name: setup-dev-env
description: "Setup development environment"

inputs:
  environment:
    default: "default"
    description:
      "Pixi environment to activate. Examples include `default`, `dev-all-py312`"

runs:
  using: composite

  steps:
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        environments: ${{ inputs.environment }}
        frozen: true
        activate-environment: ${{ inputs.environment }}
        cache-key: pixi-${{ inputs.environment }}-
