name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    default: "310"
    description: "Python version to install."
  # The current setup is to install the `dev` environment, which includes `all` dependencies
  # optional-dependencies:
  #   default: "true"
  #   description: "Install ragna with [all], i.e. all optional dependencies"

runs:
  using: composite

  steps:
    - name: Set cache date
      id: cache-key
      shell: bash
      run: |
        DATE=$(date +'%Y%m%d')
        echo "date=${DATE}" | tee -a "${GITHUB_OUTPUT}"

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      environments: dev-${{ inputs.python-version }}
      frozen: true
      activate-environment: dev-${{ inputs.python-version }}
      cache-key: pixi-${{ steps.cache-key.outputs.date }}-py${{ inputs.python-version }}-

    - name: Display Pixi info
      shell: bash -elo pipefail {0}
      run: pixi info

    - name: Display Pixi environment dependencies
      shell: bash -elo pipefail {0}
      run: pixi tree
