name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    default: "3.11"
    description: "Python version to install."

runs:
  using: composite

  steps:
    - name: Set correct Python version in environment file
      shell: bash
      run: sed -i'' -e 's/python *= *[0-9.]\+/python =${{ inputs.python-version }}/g' environment.yml

    - name: Setup mambaforge and development environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        environment-file: ./environment.yml
        activate-environment: ragna-dev

    - name: Reset environment file
      shell: bash
      run: git checkout -- environment.yml

    - name: Display conda info
      shell: bash -el {0}
      run: conda info

    - name: Install ragna
      shell: bash -el {0}
      run: pip install --editable .

    - name: Display development environment
      shell: bash -el {0}
      run: conda list
