name: setup-dev-env
description: "Setup development environment"

inputs:
  environment:
    default: "base-py310"
    description:
      "Pixi environment to activate. Examples include 'base-py310' or 'all-py313'."

runs:
  using: composite

  steps:
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        environments: ${{ inputs.environment }}
        frozen: true
        activate-environment: ${{ inputs.environment }}
        cache: false

    # - name: Install playwright
    #   shell: bash
    #   run: playwright install
