name: release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-publish:
    name: "Build Package and Publish to PyPI"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          environment: "dev-py310"

      - name: Build dists
        run: pixi run build

      - name: "Publish dists to PyPI"
        uses: "pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc"
        with:
          print-hash: true
